language: python

python:
  - "2.7"
  - "3.5"

os: linux

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - gfortran

notifications:
  email: false
   
install: source build_tools/travis/install.sh

script: nosetests
