# Container-based is prefered
sudo: false
dist: trusty

language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip   

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
   
install: source build_tools/install.sh

script: source build_tools/execute.sh

after_success: 
  - if [ ${COVERAGE} == "true" ]; then
      pip install codecov;
      codecov;
    fi
