language: python

python:
  - "2.7"
  - "3.5"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - gfortran
    - r-base-core

matrix:
  include:
    - os: linux
      compiler: gcc

notifications:
  email: false
  
cache:
  directories:
   - $HOME/.cache/pip
 
before_install:
  - R -e 'install.packages("VineCopula", repos="https://cloud.r-project.org")'

install: source build_tools/travis/install.sh

script: nosetests
