language: python

python:
  - "2.7"
  - "3.5"

os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - gfortran
    - r-base-core

notifications:
  email: false
   
before_install:
  - R -e 'install.packages("VineCopula", repos="https://cloud.r-project.org")'

install: source build_tools/travis/install.sh

script: nosetests
